import { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    title: 'Манчкин',
    description: 'Веселая карточная игра в жанре пародии на классические RPG. Побеждайте монстров, собирайте сокровища и подставляйте других игроков!',
    price: 1290,
    imageUrl: 'munchkin.png',
    category: 'Карточные игры',
    players: '3-6 игроков',
    playTime: '60-120 мин',
    age: '12',
    inStock: true,
    rating: 4.5,
  },
  {
    id: '2',
    title: 'Колонизаторы',
    description: 'Стратегическая настольная игра о развитии поселений. Стройте дороги и города, торгуйте ресурсами и станьте самым влиятельным колонизатором!',
    price: 3490,
    imageUrl: 'catan.png',
    category: 'Стратегии',
    players: '3-4 игрока',
    playTime: '60-120 мин',
    age: '10',
    inStock: true,
    rating: 5,
  },
  {
    id: '3',
    title: 'Каркассон',
    description: 'Настольная игра о строительстве средневекового города. Размещайте тайлы, отправляйте подданных и создавайте свой уникальный город!',
    price: 2790,
    imageUrl: 'carcassonne.png',
    category: 'Стратегии',
    players: '2-5 игроков',
    playTime: '30-45 мин',
    age: '7',
    inStock: false,
    rating: 4.8,
  },
  {
    id: '4',
    title: 'Диксит',
    description: 'Творческая игра с красивыми иллюстрациями. Придумывайте ассоциации, угадывайте карты и дайте волю своему воображению!',
    price: 2490,
    imageUrl: 'dixit.png',
    category: 'Вечериночные',
    players: '3-6 игроков',
    playTime: '30 мин',
    age: '8',
    inStock: true,
    rating: 4.7,
  },
  {
    id: '5',
    title: 'Ticket to Ride: Европа',
    description: 'Стратегическая игра о железнодорожных маршрутах. Стройте маршруты между городами Европы и станьте крупнейшим железнодорожным магнатом!',
    price: 3990,
    imageUrl: 'ticket-to-ride.png',
    category: 'Стратегии',
    players: '2-5 игроков',
    playTime: '60-90 мин',
    age: '8',
    inStock: true,
    rating: 4.9,
  },
  {
    id: '6',
    title: 'Имаджинариум',
    description: 'Российская игра с сюрреалистичными картинками. Развивайте воображение и находите необычные ассоциации!',
    price: 1990,
    imageUrl: 'imaginarium.png',
    category: 'Вечериночные',
    players: '3-7 игроков',
    playTime: '45 мин',
    age: '12',
    inStock: true,
    rating: 4.6,
  },
  {
    id: '7',
    title: 'Пандемия',
    description: 'Кооперативная игра о борьбе с болезнями. Работайте вместе, чтобы спасти человечество от смертельных вирусов!',
    price: 2990,
    imageUrl: 'pandemic.png',
    category: 'Кооперативные',
    players: '2-4 игрока',
    playTime: '45-60 мин',
    age: '10',
    inStock: true,
    rating: 4.8,
  },
  {
    id: '8',
    title: 'Цитадели',
    description: 'Карточная игра о строительстве средневекового города. Интриги, блеф и тактическое планирование!',
    price: 1490,
    imageUrl: 'citadels.png',
    category: 'Карточные игры',
    players: '2-7 игроков',
    playTime: '45-60 мин',
    age: '10',
    inStock: true,
    rating: 4.5,
  },
  {
    id: '9',
    title: 'Эволюция',
    description: 'Биологическая карточная игра. Развивайте свои виды, приспосабливайтесь к окружающей среде и выживайте!',
    price: 1790,
    imageUrl: 'evolution.png',
    category: 'Карточные игры',
    players: '2-4 игрока',
    playTime: '60 мин',
    age: '12',
    inStock: true,
    rating: 4.4,
  },
  {
    id: '10',
    title: 'Подземелье и драконы: Стартовый набор',
    description: 'Легендарная ролевая игра. Создавайте персонажей, исследуйте подземелья и переживайте эпические приключения!',
    price: 4990,
    imageUrl: 'dnd.png',
    category: 'Ролевые',
    players: '2-6 игроков',
    playTime: '120+ мин',
    age: '12',
    inStock: false,
    rating: 4.9,
  },
  {
    id: '11',
    title: 'Бэнг!',
    description: 'Динамичная карточная игра в стиле вестерн. Угадывайте роли других игроков и достигайте своих целей!',
    price: 990,
    imageUrl: 'bang.png',
    category: 'Карточные игры',
    players: '4-7 игроков',
    playTime: '30-40 мин',
    age: '8',
    inStock: true,
    rating: 4.3,
  },
  {
    id: '12',
    title: 'Серп',
    description: 'Стратегия в альтернативном мире 1920-х. Развивайте экономику, стройте мехов и боритесь за влияние в Восточной Европе!',
    price: 5990,
    imageUrl: 'scythe.png',
    category: 'Стратегии',
    players: '1-5 игроков',
    playTime: '90-120 мин',
    age: '14',
    inStock: true,
    rating: 4.8,
  },
];
